### ISSUE TITLE
trouble making bootable backup from sync-root

### ISSUE THREAD

**Issue by nigelhaslam** [aktos-io/dcs-tools#16]
Hi Cerem,
I've succeded with both an initial and incremental backup of my RaspberryPiZeroW and now I'm looking to make that backup into a bootable SD card image.

Here's what I get when I try to make the backup

root@raspberrypi:/media/pi/PiStore/remote-machines/zero1# ./dcs-tools/make-backu                                   p --source sync-root/ --backups bootable_backups/ --method hardlinks
Enter Comment : First_attempt_Zero_01
Creating backup with the following name: 20171119T0844-First_attempt_Zero_01
Using hardlinks method
ERROR:
ERROR:
ERROR: FIXME: invalid cross-device link error on btrfs filesystem. Below code is                                    still tested well.
ERROR:
ERROR:

This is on a Raspberry Pi B+ running the latest version of Raspbian
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"

Thanks in advance for your consideration
Nigel

**Comment by ceremcem** [comment]
Hi Nigel, 

Making backups from sync root is a completely different process from making a bootable backup. So, considering the title, `make-backup` is unrelated with this process. 

What do you get when you use `produce-bootable-disk`? For usage help, you can run it without an argument or with `--help` argument.

(Note: Please use [fenced blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) for codes)

**Comment by nigelhaslam** [comment]
Oh, ok.. thanks for your swift reply mate!

when I run '''produce-bootable-disk''' I get

'''bash: produce-bootable-disk: command not found'''

**Comment by ceremcem** [comment]
Please try `./dcs-tools/produce-bootable-disk` as it resides under the `dcs-tools` directory.

(Note: It's triple backticks: ` ``` `, not triple single quote.)

**Comment by nigelhaslam** [comment]
Ok I see the command now...
when I run it it asks for a ```--device to format and create bootable disk```
Do I need to have a second, ready to write, SD card ready, perhaps in a USB card reader?
I expected this command to produce an image file that I could copy to my windows box and burn to SD

**Comment by ceremcem** [comment]
Nope, this command directly formats the SD card and transfers the root file system to the newly created partitions. So obviously you need a different SD card than your current Raspberry has. 

# A BIG WARNING
You may destroy all of your data, and you may never be able to reach them again, ever. So make your backups properly, do not involve any valuable files in this process until you learn how to use these kind of tools
# END OF BIG WARNING

**Comment by nigelhaslam** [comment]
Ok,
So obviously I have to have two SD cards in the machine at the time.. the
one running the OS, where then dcs-tools directory and the sync root is AND
another SD card to format and write the backed up files to.
N
