### ISSUE TITLE
trouble with backups

### ISSUE THREAD

**Issue by nigelhaslam** [aktos-io/dcs-tools#17]
Hi Cerem,

When I run the backup command as follows I get an error

```pi@raspberrypi:/media/pi/PiStore/remote-machines/zero1 $ sudo dcs-tools/make-backup --source sync-root --backups bootable_backups --method hardlinks
Enter Comment : test
Creating backup with the following name: 20171126T1509-test
Using hardlinks method
ERROR:
ERROR:
ERROR: FIXME: invalid cross-device link error on btrfs filesystem. Below code is still tested well.
ERROR:
ERROR:```

I looked inside the make-backup script and can see that it's an error message from your system, not a system error, so I hope you will know what it means.

When I try to Google it, this error seems to be related to separate hard drives 

https://unix.stackexchange.com/questions/79132/invalid-cross-device-link-while-hardlinking-in-the-same-file-system

My understanding of 'hard linking' is that it's an ACTUAL copy of data, not a pointer to a single data set, am I wrong?

N

**Comment by ceremcem** [comment]
Hi Nigel, 

This exception message was left there for myself as there was such an error when I try to test the `hardlinks method` as I was refactoring the whole tool on my BTRFS filesystem. 

The original problem was that using `hardlinks method` is not possible on cross devices and even if you are on the same device, BTRFS subvolumes are treated as cross devices, so at that time I couldn't verify the `hardlinks method` is working correctly, so I left that exception for safety purposes. 

With my latest tests, I can verify that `hardlinks method` is working correctly. So https://github.com/aktos-io/dcs-tools/commit/39cfab3dcfc42cb58c17a348d097fccaba93d9e7 fixes the issue. 

You can update (`make update`) and try again.

**Comment by nigelhaslam** [comment]
awesome, thanks, I'll update and give it another go tomorrow.

Nigel

*Nigel Haslam* *| Director *

*Motion Circus Pty Ltd. Byron Bay*
*t**: + 61 2 8007 7338 **|**m**: * *+ 61  403 020 126*
*w: www.motioncircus.com <http://www.motioncircus.com/>*
link to website <http://motioncircus.com>

**Comment by ceremcem** [comment]
Nigel, 

As I was seeing you were having trouble with all these commands, I wanted to make this backup procedure a bit simpler by [`make backup-sync`](https://github.com/aktos-io/dcs-tools/issues/18) proposal. 

You can start using `make backup-sync` by simply following these steps: 

1. Upgrade `dcs-tools` (for the first time): `setup` script now creates appropriate flag files and backup/sync folders. You can re-run `./dcs-tools/setup` in your current project directory, it will not break anything. 
2. Whenever you decide to make a backup, first `make sync-root` and then `make backup-sync`. 

Hope this helps.

**Comment by nigelhaslam** [comment]
Dear Cerem,
You are so generous and helpful.

Thanks a million.

Nigel

On 26 Nov. 2017 8:51 pm, "Cerem Cem ASLAN" <notifications@github.com> wrote:

Nigel,

As I was seeing you were having trouble with all these commands, I wanted
to make this backup procedure a bit simpler by make backup-sync
<https://github.com/aktos-io/dcs-tools/issues/18> proposal.

You can start using make backup-sync by simply following these steps:

   1. Re-setup: ./dcs-tools/setup script now creates appropriate flag files
   and backup/sync folders. You can re-run ./dcs-tools/setup in your
   current project directory, it will not break anything.
   2. Whenever you decide to make a backup, first make sync-root and then make
   backup-sync.

Hope this helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aktos-io/dcs-tools/issues/17#issuecomment-346996125>,
or mute the thread

**Comment by nigelhaslam** [comment]
Hi,
I just gave it a go..

Updated the tools.

```
**pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2/dcs-tools $ ./update.sh**
updating dcs-tools...
remote: Counting objects: 34, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 34 (delta 16), reused 9 (delta 3), pack-reused 0
Unpacking objects: 100% (34/34), done.
From https://github.com/aktos-io/dcs-tools
 * branch            master     -> FETCH_HEAD
   523fd55..a0d3a9b  master     -> origin/master
Updating 523fd55..a0d3a9b
Fast-forward
 README.md                       | 72 +++++++++++++++++++++++++++++++++---------------------------------------
 doc/configuration.md            |  4 ++++
 make-backup                     |  1 -
 setup                           | 46 +++++++++++++++++++++++++++++++++++++++++-----
 toolset-make-backup.sh          | 18 ++++++++++++++++++
 Makefile => toolset-makefile.mk |  3 +++
 6 files changed, 99 insertions(+), 45 deletions(-)
 create mode 100755 toolset-make-backup.sh
 rename Makefile => toolset-makefile.mk (96%)
```
Then ran 

```
pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2 $ make sync-root
/home/pi/.ssh/id_rsa
Using source: pi@192.168.0.63:22/, port: 22 addr: 192.168.0.63, user: pi, path: /
Using sync directory: /media/pi/PiStore/remote-machines/zero2/sync-root
----------------------  YES / NO  ----------------------
Should we really continue? (yes/no) yes
syncs will go to: /media/pi/PiStore/remote-machines/zero2/sync-root
pi@192.168.0.63's password:
receiving incremental file list
dev/
etc/fake-hwclock.data
             20 100%   19.53kB/s    0:00:00 (xfr#1, ir-chk=1341/1662)
run/
tmp/
var/backups/
var/backups/apt.extended_states.0
         13.66K 100%    6.51MB/s    0:00:00 (xfr#2, ir-chk=2285/42665)
var/backups/apt.extended_states.1.gz
          1.19K 100%   77.28kB/s    0:00:00 (xfr#3, ir-chk=2284/42665)
var/lib/apt/daily_lock
              0 100%    0.00kB/s    0:00:00 (xfr#4, ir-chk=2255/42665)
var/lib/dhcpcd5/dhcpcd-wlan0-Yuminet.lease
            273 100%   10.25kB/s    0:00:00 (xfr#5, ir-chk=2235/42665)
var/lib/plymouth/boot-duration
            618 100%    1.53kB/s    0:00:00 (xfr#6, to-chk=112/43025)
var/lib/systemd/clock
              0 100%    0.00kB/s    0:00:00 (xfr#7, to-chk=105/43025)
var/lib/systemd/random-seed
            512 100%    1.04kB/s    0:00:00 (xfr#8, to-chk=104/43025)
var/lib/systemd/timers/stamp-apt-daily-upgrade.timer
              0 100%    0.00kB/s    0:00:00 (xfr#9, to-chk=27/43025)
var/lib/systemd/timers/stamp-apt-daily.timer
              0 100%    0.00kB/s    0:00:00 (xfr#10, to-chk=26/43025)
var/log/

sent 5.62K bytes  received 1.12M bytes  7.66K bytes/sec
total size is 943.48M  speedup is 840.25
sync completed in: 00:02:27
```

Then ran
```
`pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2 $ make backup-sync
ERROR:
ERROR:
ERROR: Medhod is required. Put either method-btrfs or method-hardlinks file
ERROR:
ERROR:
Makefile:71: recipe for target 'backup-sync' failed
make: *** [backup-sync] Error 1```
```
Then ran
```
pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2 $ make backup-sync method-hardlinks
ERROR:
ERROR:
ERROR: Medhod is required. Put either method-btrfs or method-hardlinks file
ERROR:
ERROR:
Makefile:71: recipe for target 'backup-sync' failed
make: *** [backup-sync] Error 1
```

Looking at the word **file** at the end of your error message, I got the feeling I needed to create a file named **method-hardlinks** and place it somewhere, so I tired that and it seems to work.

I think your error message could be clearer.. **A backup method is required - depending on the method you prefer, create a file with the name ```method-btrfs``` or ```method-hardlinks``` in your project directory.**

**Comment by nigelhaslam** [comment]
Hi again,
I feel I've made some good progress but here's where I'm stuck now.  I've put a freshly formatted MicroSD card in a USB adaptor, into my RaspberryPi and done the following
```
pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2 $ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    1 28.9G  0 disk
└─sda1        8:1    1 28.9G  0 part /media/pi/PiStore
sdc           8:32   1 14.9G  0 disk
└─sdc1        8:33   1 14.9G  0 part
mmcblk0     179:0    0   29G  0 disk
├─mmcblk0p1 179:1    0  1.6G  0 part
├─mmcblk0p2 179:2    0    1K  0 part
├─mmcblk0p5 179:5    0   32M  0 part /media/pi/SETTINGS
├─mmcblk0p6 179:6    0   69M  0 part /boot
└─mmcblk0p7 179:7    0 13.4G  0 part /
pi@raspberrypi:/media/pi/PiStore/remote-machines/zero2 $ dcs-tools/produce-bootable-disk  --backup backups --device /dev/sdc
Using backup directory: /media/pi/PiStore/remote-machines/zero2/backups
Using device: /dev/sdc
Using default ext3 type.
----------------------  YES / NO  ----------------------
Should we really continue? (yes/no) yes
Bootable device /dev/sdc will be built by using /media/pi/PiStore/remote-machines/zero2/backups
ERROR:
ERROR:
ERROR: No such partition/device can be found: /dev/sdcp1
ERROR:
ERROR:
```

It seems to be looking for sdc**p1** but the SD card is unformatted, so, of course, there are no partitions.

**Comment by ceremcem** [comment]
Nigel, 

Yes, you need to place `method-*` file in "somewhere" where the "re-setup" step (above) would do so. 

You would need to: 

```
make update 
./dcs-tools/setup  # <-- This step is missing 
make sync-root
make backup-sync
```

The `produce-bootable-disk` is not related with this problem, please rise another issue for that.
